"""
Problem:
You have been given a CSV file containing information about customer transactions. Your task is to write a Python script that processes the data and performs the following tasks:

Read the CSV file and extract the relevant columns (e.g., customer_id, product_id, purchase_amount, purchase_date).

Clean the data by removing any rows with missing or invalid values.

Aggregate the data to calculate the total purchase amount and the count of purchases for each customer.

Calculate the average purchase amount per customer.

Generate a report that includes the customer ID, total purchase amount, count of purchases, and average purchase amount for each customer.

Requirements:

Use Python to write the script.
Assume that the CSV file has a header row and the relevant columns are named customer_id, product_id, purchase_amount, and purchase_date.
Handle any potential errors or exceptions that may occur during the data processing.
You can use any Python libraries (e.g., pandas) to assist with data manipulation and analysis.
Your solution should include:

A Python script that reads the CSV file, performs the required data processing steps, and generates the report.
Sample input data (CSV file) for testing your script.
A sample output report generated by your script.

"""
import pandas as pd

# Read the CSV file and extract the relevant columns
src_file = r"C:\Users\yourname\Documents\customer_transactions.csv"
df = pd.read_csv(src_file)
transc_info = df[['customer_id', 'product_id', 'purchase_amount', 'purchase_date']]

# Clean data by removing any rows with missing or invalid values
## Drop all missing and empty values
transc_info_update = transc_info.dropna()

# Aggregate the data to calculate the total purchase amount and the count of purchases for each customer.
total_purchase_amount = transc_info_update['purchase_amount'].sum()
customer_purchase_counts = transc_info_update['customer_id'].value_counts()
# Calculate the avg purchase amount per customer
customer_purchase_amounts = transc_info_update.groupby('customer_id')['purchase_amount'].sum()
customer_avg_purchase_amounts = transc_info_update.groupby('customer_id')['purchase_amount'].mean()
# Generate the report of all this information
report = pd.DataFrame({
    'Customer ID': customer_purchase_counts.index,
    'Total Purchase Amount': customer_purchase_amounts,
    'Purchase Count': customer_purchase_counts,
    'Average Purchase Amount': customer_avg_purchase_amounts
})
print(report)
